# Generated by Django 4.2.3 on 2023-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_message_newsletter_newsletter_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиент'),
        ),
    ]
