# Generated by Django 4.2.3 on 2023-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_client_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('CR', 'Создана'), ('ST', 'Запущена'), ('CMP', 'Заврешена')], default='CR', max_length=10, verbose_name='статус рассылки'),
        ),
    ]
